### ISSUE TITLE
When due date includes a time it is not shown correctly in the cli

### ISSUE THREAD

**Issue by JovisFilius** [sachaos/todoist#106]
When adding a new task with due date and time from the CLI, this task (with due date and time) is shown correctly in the todoist android app. However, on the CLI, this same task is shown without a due date at all.
Also, when adding a due date and time from the android app this does show up correctly on the CLI.
For clarity: due dates that do not include a time are handled correctly from both sides.
See screenshots below for reference, todoist version is 0.14.0:
![image](https://user-images.githubusercontent.com/42693100/70057462-71d59580-15dd-11ea-817f-b50107482a94.png)
![image](https://user-images.githubusercontent.com/42693100/70057520-92055480-15dd-11ea-80c8-0166e60577ab.png)

Maybe I'm missing something, but I think this is a bug

**Comment by xrendan** [comment]
I have the same issue.

The root cause is that the CLI does not display times with timezones properly. By default creating the task on the app or webapp it defaults to a floating timezone (i.e due the same time across timezones).

The time is stored and cached properly by the CLI but doesn't seem to displayed properly. If I've got time over the next couple days I'll see if I can submit a PR. Go isn't really my language but if it's simple I'll do one.
