### ISSUE TITLE
Symlink issue for config file

### ISSUE THREAD

**Issue by seqizz** [sachaos/todoist#186]
Hi :wave: 

First of all, thanks for this tool!

I wanted to define the config file under my nixos system via home-manager, which puts the config file under /nix/store (world-readable) and creates a symlink for config.json in the home folder.

Which, as you can guess, fails with:
```
panic: Config file has wrong permissions. Make sure to give permissions 600 to file /home/gurkan/.config/todoist/config.json
```
which is not possible in this context. Can we set a "I know what I am doing"-style environment variable to skip that enforcement maybe? 😬

**Comment by tammersaleh** [comment]
I'm hitting this issue as well.  I like the intention of this check, but I think it might be more trouble than it's worth.  Nowadays, very few of us work in multi-user environments, and an intruder getting access to our Todoist keys isn't as crazy-bad as getting access to our private SSH keys. 

(I use SSH as an example since it's the only other tool I know of that enforces key file permissions like this)

**Comment by seqizz** [comment]
I'm closing this since:
- Looks like it's not an active repo
- I am already writing [my own client](https://git.gurkan.in/gurkan/sakla) right now
Thanks anyway :wave:
