### ISSUE TITLE
Error: bad request: 403 Forbidden

### ISSUE THREAD

**Issue by arvofm** [sachaos/todoist#202]
The program receives updates through time, yes... But the package managers that take time to update and verify certain repositories like "xbps" on Void Linux do not receive the updated version quickly. So I did a little digging and found that the error "Error: bad request: 403 Forbidden" when syncing stems from not using the updated software. I decided to build the package myself but it also gets outdated. Can we have these updates that do not result to this error, or is it already a necessary thing?

**Comment by spitzerdotorg** [comment]
This seems to have started a week or 2 ago. I get the following from debug. Maybe the API changed? I have seen that some other services have broken recently due to a Todoist API change:

myhost$ ~/go/bin/todoist --debug sync

2022/12/24 12:14:00 doAPi: called
2022/12/24 12:14:00 config: &todoist.Config{AccessToken:"REDACTED", DebugMode:true, Color:false}
2022/12/24 12:14:00 request: &http.Request{Method:"POST", URL:(*url.URL)(0xc000191290), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Content-Type":[]string{"application/x-www-form-urlencoded"}}, Body:io.nopCloserWriterTo{Reader:(*strings.Reader)(0xc00006aa80)}, GetBody:(func() (io.ReadCloser, error))(0x680a60), ContentLength:92, TransferEncoding:[]string(nil), Close:false, Host:"todoist.com", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.emptyCtx)(0xc000018068)}
2022/12/24 12:14:00 request.URL: &url.URL{Scheme:"https", Opaque:"", User:(*url.Userinfo)(nil), Host:"todoist.com", Path:"/API/v9/sync", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}
2022/12/24 12:14:00 params: &strings.Reader{s:"resource_types=%5B%22all%22%5D&sync_token=%2A&token=REDACTED", i:0, prevRune:-1}
2022/12/24 12:14:00 response: &http.Response{Status:"403 Forbidden", StatusCode:403, Proto:"HTTP/2.0", ProtoMajor:2, ProtoMinor:0, Header:http.Header{"Cache-Control":[]string{"no-cache"}, "Content-Length":[]string{"208"}, "Content-Type":[]string{"application/json"}, "Date":[]string{"Sat, 24 Dec 2022 17:14:00 GMT"}, "Referrer-Policy":[]string{"strict-origin-when-cross-origin"}, "Retry-After":[]string{"65"}, "Strict-Transport-Security":[]string{"max-age=31536000; includeSubDomains; preload"}, "Vary":[]string{"Accept-Encoding"}, "Via":[]string{"1.1 da1815f8c76e376684e7d01242493d36.cloudfront.net (CloudFront)"}, "X-Amz-Cf-Id":[]string{"NO36_ZSBpj1tKv345zMRIpndC008vQB_rFHfho5ZB0QHzH2bovSuLA=="}, "X-Amz-Cf-Pop":[]string{"BOS50-P2"}, "X-Cache":[]string{"Error from cloudfront"}}, Body:http.http2transportResponseBody{cs:(*http.http2clientStream)(0xc0001fc300)}, ContentLength:208, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc00015e500), TLS:(*tls.ConnectionState)(0xc00013a580)}
2022/12/24 12:14:00 bad request: 403 Forbidden: Invalid CSRF token
Error: bad request: 403 Forbidden

**Comment by sachaos** [comment]
I've fixed this issue in v0.18.0.
