### ISSUE TITLE
Build fails: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by childerico** [sachaos/todoist#36]
I tried to build the `todoist` package available for Arch Linux. It fails with the following error:
```
go/src/github.com/sachaos/todoist/lib/command.go:21:21: multiple-value uuid.NewV4() in single-value context
go/src/github.com/sachaos/todoist/lib/command.go:22:21: multiple-value uuid.NewV4() in single-value context
```
I am using Go 1.9.2.

**Comment by sachaos** [comment]
@childerico 
It seems that [go.uuid](https://github.com/satori/go.uuid) changed interface.
The AUR's build script does not manifest library version, so fetch the latest version of go.uuid, then the error happened.

The latest version of this project is using `dep` as package manager, and manifest library version.
So now, you can install command by build yourself instead of using AUR's package.
https://github.com/sachaos/todoist#build-it-yourself

(I will request the AUR package owner to upgrade the build script.)

**Comment by childerico** [comment]
I flagged the package on the Arch user repository as outdated. I hope that the build script will be updated soon. In the meantime, I tried to build the project manually, but it fails with a different error:

```
go install
# todoist
./add.go:24:41: client.Store.Projects.GetIDByName undefined (type todoist.Projects has no field or method GetIDByName)
./delete.go:14:25: client.CompleteItemIDByPrefix undefined (type *todoist.Client has no field or method CompleteItemIDByPrefix)
./modify.go:21:24: client.CompleteItemIDByPrefix undefined (type *todoist.Client has no field or method CompleteItemIDByPrefix)
./modify.go:49:36: client.Store.Projects.GetIDByName undefined (type todoist.Projects has no field or method GetIDByName)
```
What am I doing wrong?

**Comment by sachaos** [comment]
@childerico It's strange. Are you executed `make install` surely?

**Comment by childerico** [comment]
Yes, I just cloned the repository in `mygopath/src` and run `make install`. I cannot post the full output at the moment, but the only things printed before the error were related to `dep ensure` and `goyacc`.

**Comment by sachaos** [comment]
@childerico OK, I found the problem.
You should clone in `$GOPATH/src/github.com/sachaos/todoist`.

**Comment by childerico** [comment]
Thank you very much! That was my fault. Since the other problem with the Arch Linux package depends on the build script to be updated, I close the issue.
